name: Org Tasks

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to dev.jai.nexus (via PR)"
        type: boolean
        default: true
      subset:
        description: "Optional: repo name filter (comma-sep)"
        default: ""
  schedule:
    - cron: "15 * * * *" # hourly at :15

permissions:
  contents: read

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Create org-scoped app token
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ORG_APP_ID }}
          private-key: ${{ secrets.ORG_APP_PRIVATE_KEY }}
          owner: jai-nexus
          repositories: public-nexus
          # App installation must grant: Contents:write, Pull requests:write

      - name: Checkout .github (this repo)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Aggregate tasks (GitHub + Notion)
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          ORG: jai-nexus
          SUBSET: ${{ github.event.inputs.subset }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TASKS_DB: ${{ secrets.NOTION_TASKS_DB }}
        run: |
          set -euo pipefail
          mkdir -p out
          # Replace this with your real aggregator when ready:
          if [ -f codex/aggregate_tasks.mjs ]; then
            node codex/aggregate_tasks.mjs
          else
            echo '{"items":[{"id":"bootstrap","title":"Replace aggregate_tasks.mjs with real aggregator"}]}' > out/tasks.json
          fi
          echo "Preview (top 40 lines):"
          head -n 40 out/tasks.json || true

      - name: Upload artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: org-tasks
          path: out/tasks.json

      - name: Publish to public-nexus (branch + PR)
        if: ${{ github.event_name == 'schedule' || github.event.inputs.publish != 'false' }}
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          GIT_AUTHOR_NAME: "jai-org-hardener[bot]"
          GIT_AUTHOR_EMAIL: "bots@jai.nexus"
          GIT_COMMITTER_NAME: "jai-org-hardener[bot]"
          GIT_COMMITTER_EMAIL: "bots@jai.nexus"
        run: |
          set -euo pipefail
          export GITHUB_TOKEN="$GH_TOKEN"   # ensure gh uses the App token

          git clone --depth=1 "https://x-access-token:${GH_TOKEN}@github.com/jai-nexus/public-nexus.git" site
          mkdir -p site/data
          cp -f out/tasks.json site/data/tasks.json
          if [ -f codex/tasks_index.html ]; then
            cp -f codex/tasks_index.html site/index.html
          fi

          cd site
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to publish."; exit 0
          fi

          branch="org-tasks-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$branch"
          git commit -m "site(tasks): automated update of org tasks JSON + UI"
          git push origin "$branch"

          gh pr create \
            --repo jai-nexus/public-nexus \
            --head "$branch" \
            --base main \
            --title "site(tasks): update org tasks" \
            --body "Automated update from .github/org_tasks workflow."
