name: Org Tasks

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to dev.jai.nexus (via PR)"
        type: boolean
        default: true
      subset:
        description: "Optional: repo name filter (comma-sep)"
        default: ""
  schedule:
    - cron: "15 * * * *" # hourly at :15

# prevent overlapping runs that cause PR/branch spam
concurrency:
  group: public-nexus-org-tasks
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Create org-scoped app token
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ORG_APP_ID }}
          private-key: ${{ secrets.ORG_APP_PRIVATE_KEY }}
          owner: jai-nexus
          repositories: public-nexus
          # NOTE: App installation must grant at least: Contents:write, Pull requests:write

      - name: Checkout .github (this repo)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Aggregate tasks (GitHub + Notion)
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          ORG: jai-nexus
          SUBSET: ${{ github.event.inputs.subset }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TASKS_DB: ${{ secrets.NOTION_TASKS_DB }}
        run: |
          set -euo pipefail
          mkdir -p out
          # Replace this with your real aggregator when ready:
          if [ -f codex/aggregate_tasks.mjs ]; then
            node codex/aggregate_tasks.mjs
          else
            echo '{"items":[{"id":"bootstrap","title":"Replace aggregate_tasks.mjs with real aggregator"}]}' > out/tasks.json
          fi
          echo "Preview (top 40 lines):"
          head -n 40 out/tasks.json || true

      - name: Upload artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: org-tasks
          path: out/tasks.json

      # --------- PUBLISH: single branch + single PR (no homepage overwrite) ---------
      - name: Publish to public-nexus (single branch + PR)
        if: ${{ github.event_name == 'schedule' || github.event.inputs.publish != 'false' }}
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          GIT_AUTHOR_NAME: "jai-org-hardener[bot]"
          GIT_AUTHOR_EMAIL: "bots@jai.nexus"
          GIT_COMMITTER_NAME: "jai-org-hardener[bot]"
          GIT_COMMITTER_EMAIL: "bots@jai.nexus"
        run: |
          set -euo pipefail
          export GITHUB_TOKEN="$GH_TOKEN"   # ensure gh uses the
