name: Org Tasks
on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to dev.jai.nexus"
        type: boolean
        default: true
      subset:
        description: "Optional: repo name filter (comma‑sep)"
        default: ""
  schedule:
    - cron: "15 * * * *"  # hourly at :15

permissions:
  contents: read

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
      - name: Create org-scoped app token
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ORG_APP_ID }}
          private-key: ${{ secrets.ORG_APP_PRIVATE_KEY }}
          owner: jai-nexus
          repositories: public-nexus
          # (Optional) You can request narrowed perms, but VS Code often flags schema:
          # permissions: >-
          #   {"contents":"write","actions":"write"}

      - name: Checkout .github (this repo)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Aggregate tasks (GitHub + Notion)
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          ORG: jai-nexus
          SUBSET: ${{ inputs.subset }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TASKS_DB: ${{ secrets.NOTION_TASKS_DB }}
        run: |
          set -euo pipefail
          node codex/aggregate_tasks.mjs
          echo "Preview (top 40 lines):"
          head -n 40 out/tasks.json || true

      - name: Upload artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: org-tasks
          path: out/tasks.json
      - name: Publish to public-nexus (when enabled)
        # publish on schedule OR when the boolean input is true
        if: ${{ github.event_name == 'schedule' || inputs.publish }}
        env:
          GIT_AUTHOR_NAME: "jai-org-hardener[bot]"
          GIT_AUTHOR_EMAIL: "bots@jai.nexus"
          GIT_COMMITTER_NAME: "jai-org-hardener[bot]"
          GIT_COMMITTER_EMAIL: "bots@jai.nexus"
        run: |
          set -euo pipefail

          # clone the site repo with the App token
          git clone --depth=1 https://x-access-token:${{ steps.app.outputs.token }}@github.com/jai-nexus/public-nexus.git site

          # drop in JSON
          mkdir -p site/data
          cp -f out/tasks.json site/data/tasks.json

          # drop in UI from repo (added in step 4)
          if [ -f codex/tasks_index.html ]; then
            cp -f codex/tasks_index.html site/index.html
          fi

          cd site
          git add -A
          git commit -m "site(tasks): publish org tasks JSON + UI bootstrap" || echo "no changes"
          git push origin main

      - name: Publish to public-nexus (when enabled)
        # Publish if scheduled OR if workflow_dispatch publish != 'false'
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.publish != 'false' }}
        env:
          GIT_AUTHOR_NAME: "jai-org-hardener[bot]"
          GIT_AUTHOR_EMAIL: "bots@jai.nexus"
          GIT_COMMITTER_NAME: "jai-org-hardener[bot]"
          GIT_COMMITTER_EMAIL: "bots@jai.nexus"
        run: |
          set -euo pipefail

          # clone the site
          git clone --depth=1 https://x-access-token:${{ steps.app.outputs.token }}@github.com/jai-nexus/public-nexus.git site

          # drop in JSON
          mkdir -p site/data
          cp -f out/tasks.json site/data/tasks.json

          # drop in UI from repo (added as codex/tasks_index.html)
          if [ -f codex/tasks_index.html ]; then
            cp -f codex/tasks_index.html site/index.html
          fi

          cd site
          git add -A
          git commit -m "site(tasks): publish org tasks JSON + UI bootstrap" || echo "no changes"
          git push origin main
